[package]
name = "wildbloomd"
description = "Headless cross-platform Wildbloom Blossom node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
clap.workspace = true
directories.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
wildbloom-core.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[dev-dependencies]
base64.workspace = true
hex.workspace = true
nostr.workspace = true
reqwest.workspace = true
sha2.workspace = true
tempfile.workspace = true
